---
# tasks file for nodejs
    - name: Install Epel Release.
      yum: name=epel-release state=present

    - name: Upgrade all Packages.
      yum: name=* state=latest

    - name: Stopped Firewall for test environment.
      service: name=firewalld state=stopped

    - name: Install Node Package Manager.
      yum: name=npm state=present enablerepo=epel

    - name: Install Forever to run Nodejs.
      npm: name=forever global=yes state=present

    - name: Ensure Node.js app folder exist.
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example Node.js app to Server.
      copy: "src=files dest={{ node_apps_location }}"

    - name: Install app dependencies defined in package.json.
      npm: path={{ node_apps_location }}/files

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location}}/files/app.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/files/app.js') == -1"
