---
# tasks file for nodejs_install
    - name: Install Remi Repo.
      yum:
         name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
         state: present

    - name: Import Remi GPG Key.
      rpm_key:
         key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
         state: present